import { VeChainKitProviderWrapper } from "@/utils/VeKitProvider";
import AppHeader from "@/utils/header";
import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <VeChainKitProviderWrapper>
          <AppHeader />
          {children}
        </VeChainKitProviderWrapper>
      </body>
    </html>
  );
}
